# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - scripts
      - recomendation/lib
      - src
      - .pipelines/template/template-model-download.yml
resources:
- repo: self

variables:
  - name: workingDirectoryScripts
    value: '$(Build.SourcesDirectory)'
  - name: workingDirectoryInferencing
    value: '$(Build.SourcesDirectory)'
  - name: mlModelArtifact
    value: 'azureml-app'
  - name: vmImageName
    value: 'ubuntu-latest'


stages:
  - stage: dev
    variables:
      - group: test
    jobs:
      - job: inferencing_service_ci_download
        displayName: 'Download ML model'
        pool:
          vmImage: $(vmImageName)
        steps:
          - template: ./template/template-model-download.yml
            parameters:
              artifactName: $(mlModelArtifact)
              modelName: 'anomaly_model'
              resourceGroupName: 'kush-res-grp'
              servicePrincipalId: '972124e4-73b0-419c-8b53-510f4b7f8e43'
              servicePrincipalSecret: $(secret)
              tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
              workingDir: $(workingDirectoryScripts)
              workingDirInferencing: $(workingDirectoryInferencing)
              workspaceName: 'MLTest'

