# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Definition of infra-related environment variables

variables:

  # DEV Environment
  ENVIRONMENT: DEV
  RESOURCE_GROUP: rg-mlops-dev-001
  LOCATION: westeurope
  NAMESPACE: mlopsdev001
  AMLWORKSPACE: aml$(NAMESPACE)
  STORAGEACCOUNT: sa$(NAMESPACE)
  KEYVAULT: kv$(NAMESPACE)
  APPINSIGHTS: ai$(NAMESPACE)
  CONTAINERREGISTRY: cr$(NAMESPACE)
  SERVICECONNECTION_RG: conn-mlops-sub-infra
  SERVICECONNECTION_WS: conn-mlops-aml-bsc-dev-001
